name: ml_capstone
channels:
    - bioconda
    - conda-forge
dependencies:
    - python==2.7.13
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - pandas
    - xgboost
    - libgcc
    - seaborn
    - pip:
        - mlxtend
